server {
    listen 80 default_server;
    server_name _;

    root /app/phorge/webroot;
    index index.php;

    client_max_body_size 256m;
    client_body_timeout 60s;

    location / {
        index index.php;
        rewrite ^/(.*)$ /index.php?__path__=/$1 last;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param REDIRECT_STATUS 200;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass unix:/run/php-fpm/phorge.sock;
    }

}
