#!/bin/sh
set -eu

case "${PHORGE_AUTO_STORAGE_UPGRADE:-1}" in
    1|true|yes)
        ;;
    0|false|no)
        echo "phorge-storage-upgrade: automatic schema upgrades are disabled"
        exit 0
        ;;
    *)
        echo "phorge-storage-upgrade: PHORGE_AUTO_STORAGE_UPGRADE must be 0 or 1" >&2
        exit 1
        ;;
esac

exec /opt/phorge/bin/storage upgrade --force
